### ISSUE TITLE
Add AAC+ support

### ISSUE THREAD

**Issue by khrynczenko** [khrynczenko/RadioStream#2]
BASS library supports MP3/MP2/MP1/OGG/WAV/AIFF out of the box. AAC+ is one of the most popular coding formats use by Internet radio stations. Possible solution is using one of official addons from the BASS webpage.

**Comment by JenioPY** [comment]
Somehow AAC+ work "out of the box" on Windows (I suppose its just not documented). But on linux this still needs to be resolved.

**Comment by khrynczenko** [comment]
Resolved in #71
